server:
  port: 8888
spring:
  zipkin:
    enabled: true
    base-url: http://10.108.2.93:9411
    service:
      name: git-config-server
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          default-label: master
          skip-ssl-validation: true
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN_KEY}