server:
  port: 7073
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123456789
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: root
      database: ECommercePost

redis:
  host: localhost
  port: 6379
